[GOORM-42] 가족 질문 생성, 조회 API 작성
9oormthonUNIV-3th-KGU/family-note-server pull request #9
Opened 2024-09-11 14:59 UTC by mingmingmon

### 📍[GOORM-42] 가족 질문 생성, 조회 API 작성

## *⛳️ Work Description*
- 가족 질문 생성 API 작성
- 가족 질문 조회 API 작성 (페이지네이션 적용)

## *📸 Screenshot*

- 기본 질문이 0개인 경우 예외처리
![image](https://github.com/user-attachments/assets/c4953c51-4462-40cb-a247-f1aa4fc0f239)
- 페이지네이션을 적용한 가족 질문 조회
![image](https://github.com/user-attachments/assets/ae24fbec-e14f-4da6-a2f8-64270d1a455a)
- 가족 질문 생성하기
![image](https://github.com/user-attachments/assets/d8cec166-679c-4e31-bba2-b9dc59eb6d3f)
- 기본 질문을 모두 가족 질문으로 등록한 경우 예외처리
![image](https://github.com/user-attachments/assets/53df128a-2295-4303-8197-60d167321ce1)

*📢 To Reviewers*
- 가족 질문 생성 시 모든 가족 구성원이 답변하지 않은 경우 생성 불가 로직을 아직 구현하지 않았어요. **다음 작업인 가족 답변 도메인과 연관된 로직이 있어서** `createFamilyQuestion()`에 주석으로 설명해두었습니다.
- **이전작업에서 잘못 작성한** BaseQuestionController의 스키마 설정을 수정하였어요.
- sever error 발생 시 **인텔리제이의 콘솔에 로그가 보였으면 좋겠어서** 해당 부분에 `log.error` 코드를 추가했어요.
- **가족 질문 생성 시 중복 질문이 없도록 하기 위해** 고민하다가 BaseQuestion과 FamilyQuestion의 역할을 분명히 하는 방향으로 구현해보았어요. 8025c3881d7722f8359450e3b9adc5263dd8eccd에서 작업하였고, 더 좋은 방향이 있다면 얼마든지 제시해주세요.
- 가족 질문 조회 시 페이지네이션을 사용하였어요. 기존에 구현된 `PageableResponse`에서 **수정된 부분이 꽤 있으니 확인**해주시고 질문사항 있으시면 남겨주세요.

2024-09-12 07:06 UTC, LeeHanEum requested changes
코드 리뷰 완료했습니다!
꼼꼼하게 확인해주시고 수정 부탁드립니다~
복잡한 API 설계하시느라 고생 많으셨어요 👍

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/response/PageableResponse.java
> +	List<T> content
PageableResponse 사용 방식에 대해 설명드리지 못한 부분이 있어 보충합니다.

PageableResponse는 content에 직접 데이터를 넣기보다는, 
ListResponse처럼 별도의 클래스를 생성하고, 그 클래스의 필드로 PageableResponse를 포함시키는 방법을 권장합니다.
또한, 저는 isEnd와 같은 필드를 구현하기 위해 of 메서드에 계산 로직을 추가했습니다. 
이 방식이 도메인 규칙을 해당 객체 내에서 관리하는 DDD 아키텍처 원칙에 부합한다고 생각합니다.

PageableResponse는 다음 예시 코드처럼 사용하시면 됩니다.
```java
public record FullInactiveMeetingQuestionListResponse<T>(
	@Schema(
		description = "비활성화된 모임 질문 목록",
		requiredMode = REQUIRED
	)
	List<FullInactiveMeetingQuestionListResponseDetail> contents,

	@Schema(description = "페이징 정보", requiredMode = REQUIRED)
	PageableResponse<T> pageable
) {

	public static FullInactiveMeetingQuestionListResponse of(List<MeetingQuestion> meetingQuestions,
		PageableResponse pageableResponse) {
		List<FullInactiveMeetingQuestionListResponseDetail> responseDetails = FullInactiveMeetingQuestionListResponseDetail.from(
			meetingQuestions);

		return new FullInactiveMeetingQuestionListResponse(responseDetails, pageableResponse);
	}
}
```

마지막으로, 다른 협업자가 작성한 메서드나 API를 수정하거나 삭제할 때에는 사전에 동의를 구하는 것이 중요하다고 생각합니다.
그 의도나 목적을 바로 파악하기 어려울 수 있으므로, 협의를 통해 더 나은 결과를 낼 수 있을겁니다.
앞으로 이 점을 유의해주시면 감사하겠습니다! 👍

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/exception/GlobalExceptionHandler.java
> +		log.error("An error occurred: {}", exception.getMessage(), exception);
500 서버 에러가 발생했을 때 로그 어떻게 찍히는지 스크린샷을 볼 수 있을까용?

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/util/RandomNumberUtils.java
> +public class RandomNumberUtils {
RandomNumberUtil 만든거 좋은 아이디어 같습니다. 👍

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/family/member/application/FamilyMemberService.java
> +		return familyService.getFamilyById(familyMember.getId());
DDD 아키텍처에서 하위 애그리거트가 상위 애그리거트에 의존하는 것은 권장되지 않습니다.
해당 로직을 상위 애그리거트인 Family의 FamilyService로 이동시키는 것은 어떨까요?

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/application/BaseQuestionService.java
> +        log.info(String.valueOf(questionIndex));
혹시 인덱스 넘버 로그 찍은 이유가 있을까용?
저는 불필요하다고 생각했는데 의도가 궁금합니다!

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/presentation/exception/BaseQuestionExceptionCode.java
> +    INVALID_BASE_QUESTION_COUNT(UNPROCESSABLE_ENTITY, "기본 질문이 0개 이하입니다."),
422 에러 보내는거 좋은 것 같습니다! 
상태 코드 숫자 순서에 맞게 마지막으로 이동 부탁드립니다~
404 -> 409 -> 422

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +@RequestMapping("/api/v1/question/family")
상위 애그리거트가 엔드포인트에서 더 앞에 와야하지 않을까요?
`/family/question` 형식은 어떠신가요?

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +            @ApiResponse(
여기도 순서 지켜주세요~

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +                    content = @Content(schema = @Schema(implementation = PageableResponse.class))
PageableResponse를 반환하면 프론트 분들이 스웨거에서 스키마를 조회할 때 어떤 데이터가 날라오는지 확인할 수 가 없어요.
위 코드리뷰에서 설명한대로 별도의 클래스로 DTO를 분리하고 해당 클래스를 스키마 값으로 넣어주세요~
이름은 `FamilyQuestionPageResponse` 추천!!

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +    @ResponseStatus(OK)
200일때는 명시하지 않아도 괜찮아요~ CREATED 처럼 다른 200번대 에러를 보낼때만 필요합니다

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +            @RequestParam(defaultValue = "0") int page,
page 및 size에 유효성 검증 어노테이션 넣어주세요. 
`@Positive` 또는 `@PositiveOrZero` 같은거 넣어주시고
스웨거 docs를 위해 `@Parameter` 어노테이션도 추가 부탁드립니다. 
제가 작업한 다른 Controller 코드 참고!!

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/application/FamilyQuestionService.java
> +    }
개행 추가 해주세요~

2024-09-12 07:06 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/presentation/response/FamilyQuestionResponseList.java
> +public record FamilyQuestionResponseList() {
요거 불필요하면 삭제 해주세요~

2024-09-12 14:02 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/common/exception/GlobalExceptionHandler.java
> +		log.error("An error occurred: {}", exception.getMessage(), exception);
1. 아래 사진은 가족질문 생성 로직에서 예외처리를 주석처리하고, `RandomNumberUtils`의 `getRandomIntInRange`메소드에서 고의적으로 에러를 발생시킨 상황입니다. 

에러가 발생한 상황에 대한 로그를 trace back으로 확인할 수 있습니다.` log.error` 코드가 없는 경우에는 API 응답으로 500 SERVER_ERROR가 띄워지지만, 콘솔에서는 구체적으로 어느 포인트에서 발생한 것인지 파악할 수 없어서 추가했습니다.

2. 추가적으로 `eventPublisher.publishEvent(exception);`의 역할에 대해서 설명해주실 수 있을까요? 로깅을 위한 수단인지, 만약 그렇다면 제가` log.error `코드를 추가하지 않고 다른 방식으로 에러 상황에 대한 설명을 볼 수 있나 싶어서 궁금했습니다
![image](https://github.com/user-attachments/assets/48cb7ffd-9b1b-4719-b4d7-a84b1888ddbc)

2024-09-12 14:05 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/application/BaseQuestionService.java
> +        log.info(String.valueOf(questionIndex));
앗 제가 인덱스값 랜덤하게 잘 나오는지 확인한다고 만들어놓았는데 삭제 안 했었네요..
[0c465ec](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/0c465ec0103d81e4804fe4c553a260174718ae76) 해당 커밋에서 삭제하였습니다

2024-09-12 14:08 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/presentation/exception/BaseQuestionExceptionCode.java
> +    INVALID_BASE_QUESTION_COUNT(UNPROCESSABLE_ENTITY, "기본 질문이 0개 이하입니다."),
[75acf73](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/75acf736c1c4c1681e379f4342f658a7258be266)에서 수정하였습니다!

2024-09-12 14:13 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +    @ResponseStatus(OK)
[a899bef](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/a899bef90223f00b06b4308eb4ef431a4a25a050) 에서 수정하였습니다!

2024-09-12 14:13 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +            @ApiResponse(
[a899bef](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/a899bef90223f00b06b4308eb4ef431a4a25a050)에서 정렬 완료하였습니다!

2024-09-12 14:28 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/application/FamilyQuestionService.java
> +    }
[da0e504](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/da0e5046eed5db42bd4e17ff1e8f96dd04c4d3f6) 에서 적용했습니다!

2024-09-12 14:28 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/presentation/response/FamilyQuestionResponseList.java
> +public record FamilyQuestionResponseList() {
[da0e504](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/da0e5046eed5db42bd4e17ff1e8f96dd04c4d3f6)에서 삭제했어요!

2024-09-12 14:58 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/common/response/PageableResponse.java
> +	List<T> content
어떤 형태로 구현해야 할 지 이해했습니다! 
다만, 제가 DDD가 익숙하지 않아 제가 이해한 내용이 맞는지 다시 확인하고자 해요.

1.  >이 방식이 도메인 규칙을 해당 객체 내에서 관리하는 DDD 아키텍처 원칙에 부합한다고 생각합니다.

라고 설명해주신 부분은 `PageableResponse` 객체에서 다뤄야 하는 `isEnd` 필드를 제가 수정한 방식대로 `Page<T>`로 받아서 `page.isLast()`로 처리하게 되면  `PageableResponse` 외부의 정보를 참조하는 것이기에 DDD 아키텍처 원칙을 위배한다고 생각하신 거죠? 

2. `content`를 직접 `PageableResponse`에 추가하지 않고, 실질적인 데이터와 페이지네이션 정보를 분리해서 DTO로 묶어 보내는 형식을 이번에 새롭게 접해보았어요. 이 또한 도메인 내의 관심사를 명확히 하고, 책임을 분리하는 것으로 DDD 원칙을 위해 택한 방식일까요?

2024-09-12 15:07 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +@RequestMapping("/api/v1/question/family")
해당 URL 설계 시에 애그리거트 관련해서 헷갈리는 부분이 있었어요. DDD 설계를 제대로 해본 적 없어서 아래의 설명에서 잘못된 부분이 있다면 알려주세요!

현재 `FamilyQuestion`이 포함되어있는 패키지가 `question`으로 설정되어 있습니다. 
즉, `Question`을 상위 애그리거트라고 생각했고, 그 아래에 하위 애그리거트로 `baseQuestion`과 `familyQuestion`이 존재한다고 생각했어요.

따라서 `baseQuestion`의 URL은` /question/base`, `familyQuestion`의 URL은 `/question/family`라고 설계해보았습니다. Restful하게 question이라는 자원 아래에 기본 또는 가족으로 분류할 수 있는 자원이 있다고 생각했어요.

2024-09-12 15:17 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/response/PageableResponse.java
> +	List<T> content
1. 네 맞습니다. isEnd 필드에 대한 가공은 PageableResponse 객체 안에서 이뤄줘야 합니다

2. 이것은 DDD 원칙과는 그다지 연관은 없어보입니다. 별도의 클래스에 PageableResponse 객체를 추가해야 하는 이유는 크게 두가지가 있을 것 같습니다. (1) 현재 저희 프로젝트에서는 응답 dto마다 별도의 클래스로 분리하고 있습니다. ~~ListResponse 형식으로요. 통일성을 위해 ~~PageResponse라는 별도의 클래스로 분리하는게 좋아보입니다. (2) 아래 코드리뷰에서 적은 것처럼 최종적인 응답 DTO가 PageableResponse이면 프론트 개발자가 Swagger로 스키마를 조회할 때도 PageableResponse로 보여지게 해야합니다. 그러면 저희가 스키마 정보를 알려주는게 의미가 없어지겠죠?

충분히 답변이 되었을까요?

2024-09-12 15:29 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/common/response/PageableResponse.java
> +	List<T> content
넵 이해했습니다. 감사합니다!

2024-09-12 15:59 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/exception/GlobalExceptionHandler.java
> +		log.error("An error occurred: {}", exception.getMessage(), exception);
<img width="2242" alt="스크린샷 2024-09-13 오전 12 50 30" src="https://github.com/user-attachments/assets/f1d5af53-f962-4404-9a91-fd21d1e303aa">

음 제가 500에러를 유발시켰을 때는 LoggingAspect에서 예외를 잘 잡아서 처리하는 모습입니다.
아마 민주님 코드에서 500에러가 나지 않았던 이유는 패키지 구조가 AOP 포인트컷에 명시된 것과 달라서 그런 것 같습니다. 
현재 모든 로깅은 AOP가 관할하고 있기 때문에 GlobalExceptionHandler는 예외를 잡아서 구분해주는 역할만 수행하고 로그를 출력하지 않았으면 하는 것이 제 의견 입니다.

이벤트는 DDD 아키텍처에서 시스템간 강결합을 줄여주는 역할을 수행합니다. 
이전에는 이벤트를 처리하기 위해 별도의 테이블을 사용하였다면, EventPublisher와 EventListener를 활용하여
특정 이벤트 예를 들면 500에러 같은 것이 발생하였을 때 트리거 동작을 수행 시킬 수 있습니다. 

현재는 도메인 기능 구현이 우선이니 해당 작업에 집중하고, 추후 시간이 남으면 모니터링 툴과 결합한 이벤트 처리를 시도해볼 수 있겠습니다.

2024-09-12 16:19 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +@RequestMapping("/api/v1/question/family")
답변 해드렸습니다~

2024-09-13 12:32 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +@RequestMapping("/api/v1/question/family")
[1fdacb9](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/1fdacb97330f18a8bd7bb587527d5298899b0389) 에서 디렉토리 이동과 엔드포인트 수정하였습니다!

2024-09-13 12:51 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/family/member/application/FamilyMemberService.java
> +		return familyService.getFamilyById(familyMember.getId());
[a32e406](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/a32e406d62ae00d51ead269af9f05687062bbdaa)에서 수정하였습니다!

2024-09-13 13:09 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/common/response/PageableResponse.java
> +	List<T> content
[31a6c8c](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/31a6c8c81267281de208879e6ee8f641b28f20d3)해당 커밋에서 기존의 Pageable 형태로 다시 수정하고 설명해주신 페이지네이션 응답 컨벤션을 적용했습니다!

2024-09-13 13:09 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/common/exception/GlobalExceptionHandler.java
> +		log.error("An error occurred: {}", exception.getMessage(), exception);
넵 설명감사합니다 :)

2024-09-13 13:09 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +                    content = @Content(schema = @Schema(implementation = PageableResponse.class))
[31a6c8c](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/31a6c8c81267281de208879e6ee8f641b28f20d3)에서 수정해주었습니다!

2024-09-13 13:10 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/familyQuestion/FamilyQuestionController.java
> +            @RequestParam(defaultValue = "0") int page,
[31a6c8c](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/31a6c8c81267281de208879e6ee8f641b28f20d3)에서 RequestParam에 대한 유효성 검증 어노테이션과 스웨거 관련 어노테이션을 추가해주었습니다!

2024-09-13 15:49 UTC, LeeHanEum approved these changes
코멘트 확인해주시고 머지 해주세요. 
코드 리뷰 잘 반영해주셔서 감사합니다 👍

2024-09-13 15:49 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/family/familyQuestion/presentation/response/FamilyQuestionPageResponse.java
> +                description = "가족 질문 리스트",
ListResponse처럼 example 넣어주세요~

2024-09-13 15:49 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/family/familyQuestion/presentation/response/FamilyQuestionResponse.java
> +                return new FamilyQuestionResponse(
저는 빌더로 처리하긴 했는데 요건 알아서 판단해주십숑

2024-09-13 15:49 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/application/BaseQuestionService.java
> +@Slf4j
Slf4J 안쓰면 삭제해주세요

2024-09-13 15:49 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/presentation/BaseQuestionController.java
> +                    content = @Content(schema = @Schema(implementation = BaseQuestionResponseList.class))
이제 보니까 DTO 명이 BaseQuestionListResponse로 바껴야할것 같네용
별로 안중요하니까 킵해두고 나중에 일괄 수정하시져.
그리고 POST 요청에서는 id 정도만 담은 PersistResponse로 보내는게 좋을 것 같습니다.

2024-09-13 15:49 UTC, LeeHanEum commented on src/main/java/goorm/kgu/familynote/common/exception/GlobalExceptionHandler.java
> +		log.error("An error occurred: {}", exception.getMessage(), exception);
log.error 제거 됬나요?

2024-09-14 01:48 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/family/familyQuestion/presentation/response/FamilyQuestionResponse.java
> +                return new FamilyQuestionResponse(
아래처럼 지금 프로젝트의 dto 생성 방식이 new로 되어있어서 통일해본 것인데, 이 부분도 builder 사용하실지, new 사용하실지 나중에 리팩토링 때 정하실까요??

```
public record FamilyMemberResponse(
	Long familyMemberId,
	String nickName,
	String role
) {

	public static List<FamilyMemberResponse> of(List<FamilyMember> familyMembers) {
		return familyMembers.stream()
			.map(FamilyMemberResponse::of)
			.collect(Collectors.toList());
	}

	public static FamilyMemberResponse of(FamilyMember familyMember) {
		return new FamilyMemberResponse(
			familyMember.getId(),
			familyMember.getUser().getNickname(),
			familyMember.getRole()
		);
	}
}
```

2024-09-14 01:54 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/application/BaseQuestionService.java
> +@Slf4j
[5461b80](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/5461b807b7ad114efbab4159f00a35aaeb511031)에서 log.error와 함께 삭제하였습니다.

2024-09-14 02:11 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/question/baseQuestion/presentation/BaseQuestionController.java
> +                    content = @Content(schema = @Schema(implementation = BaseQuestionResponseList.class))
[70a2911](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/70a29115351846ae7d187dcec42deeac5b548dda)에서 PersistListResponse를 반환하도록 수정했습니다!

2024-09-14 02:12 UTC, mingmingmon commented on src/main/java/goorm/kgu/familynote/domain/family/familyQuestion/presentation/response/FamilyQuestionPageResponse.java
> +                description = "가족 질문 리스트",
[e80f0d1](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/pull/9/commits/e80f0d19d775f1cfe922516478de30ca76493104)에 반영하였습니다!

2024-09-14 02:14 UTC, merged